services:
  node-artela:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: artela-node
    ports:
      - "30656:30656"
      - "30660:30660"
    restart: unless-stopped
    volumes:
      - artela_volume:/app/.artelad
      - ./entrypoint.sh:/app/entrypoint.sh
      - artela_bin:/app/go

volumes:
  artela_volume:
  artela_bin:
